// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'delete': string;
  'done': string;
  'dragenter': string;
  'dragging': string;
  'installButton': string;
  'installContainer': string;
  'todoApp': string;
  'todoDrawer': string;
  'todoHeader': string;
  'todoInput': string;
  'todoList': string;
}
export const cssExports: CssExports;
export default cssExports;
